# Usa uma imagem do Node.js como base para o ambiente de construção
FROM node:18 AS build

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Copia os arquivos `package.json` e `package-lock.json` para instalar dependências
COPY package.json package-lock.json ./

# Instala as dependências
RUN npm install

# Copia o restante dos arquivos do projeto
COPY . .

# Compila o projeto
RUN npm run build

# Usa uma imagem do Nginx para servir os arquivos estáticos
FROM nginx:alpine

# Copia os arquivos estáticos do build para o diretório padrão do Nginx
COPY --from=build /app/dist /usr/share/nginx/html

# Expõe a porta 80 para o Nginx
EXPOSE 80

# Inicia o Nginx
CMD ["nginx", "-g", "daemon off;"]
