# frozen_string_literal: true

source 'https://mirrors.aliyun.com/rubygems/'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.2.6'

gem 'pg'
gem 'httparty'
gem 'rswag'

# Rails versão 7, a mais recente está sendo utilizada
gem 'rails', '~> 7.0.7', '>= 7.0.7.2'

# Para o banco de dados SQLite, se necessário
gem 'sqlite3', '~> 1.4'

# Use o Puma como servidor web
gem 'puma', '~> 5.0'

# Para construir APIs em JSON facilmente
gem 'jbuilder'

# Se precisar manipular imagens com Active Storage
# gem "image_processing", "~> 1.2"

# Para permitir CORS
gem 'rack-cors'

# Gems para integração com o Webpacker e pré-compilação de assets
gem 'webpacker', '~> 5.4' # Versão recomendada para projetos que ainda usam webpacker com Rails 7
gem 'sass-rails', '>= 6'  # Para compilar Sass
gem 'uglifier', '>= 1.3.0'  # Para minificação de JavaScript

# Acelera o tempo de inicialização através de caching
gem 'bootsnap', require: false

# Para lidar com problemas de fuso horário no Windows
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

group :development, :test do
  # Gems para depuração e testes
  gem 'byebug'
  gem 'debug', platforms: %i[mri mingw x64_mingw]
  gem 'rubocop-rspec'
  gem 'rubocop'
  gem 'rubocop-rails'
end

group :development do
  # Gems de desenvolvimento
  gem 'rspec-rails'
end

# Gem para pré-compilação de assets, caso esteja utilizando assets no Rails
gem 'rails_12factor', group: :production   # Para produção no Heroku ou em outros ambientes
